### PR TITLE
Add git branch option

### PR DESCRIPTION
**Pull request by andyexeter**
Implementation of my feature request in #215

This PR adds a `--git-branch` option to the `new` command, allowing developers to override the default `main` branch name.

### CODE REVIEW

**Comment by wouterj** [comment]
What about, instead of adding a flag, using `init.defaultBranch` ?

**Comment by tucksaun** [comment]
I guess it has been done to simplify SymfonyCloud/Platform.sh onboarding as well as simplifying starting working with the Fast Track.
Do you confirm @fabpot ?

If that is the case maybe we can force the branch in those cases and rely on the default git config otherwise ?

**Comment by fabpot** [comment]
@tucksaun You're right.

**Comment by tucksaun** [comment]
@fabpot 👍 

what about this alternative approach then: #235 ?

**Pull request closed without merging**
