### PR TITLE
Enable the local proxy as a service on macOS

### PR DESCRIPTION
**Pull request by tucksaun**
I always forget to start it after restart so I propose we make the Formula create the service automatically

### CODE REVIEW

**Comment by fabpot** [comment]
Makes sense. That will work for Linux as well I suppose.

**Comment by tucksaun** [comment]
I suppose so if one is using homebrew.
But I never used homebrew on Linux so I can't be sure.

**Comment by fabpot** [comment]
Thank you.

**Comment by tucksaun** [comment]
Regarding Linux, and for the record, support would need more work:

Basically one would need to:
1. add required files (mainly service definition but also script to enable the service) in this repo
2. configure GoReleaser to include files in the packages and run scripts after install (see https://goreleaser.com/customization/nfpm/)

From my experience (implementing this back then for Blackfire's agent packaging) step 1 requires quite some work and some time to be implemented properly and cross platform.
But if someone wants to work on this it looks like nFPM team did a good job on writing a good starting point: https://nfpm.goreleaser.com/tips/?h=service

**Pull request merged**
