### PR TITLE
Ignore generated binary

### PR DESCRIPTION
**Pull request by yguedidi**
I committed this file by mistake in my first PR, so maybe it's worth ignoring it

### CODE REVIEW

**Review by tucksaun — APPROVED** [review]

**Comment by fabpot** [comment]
I don't think this is useful as this name is not referenced anywhere, so when you compile the binary yourself, you can use any name.

**Comment by yguedidi** [comment]
> I don't think this is useful as this name is not referenced anywhere, so when you compile the binary yourself, you can use any name.

@fabpot I just run `go generate` then `go build` and this the filename I got

**Comment by fabpot** [comment]
> > I don't think this is useful as this name is not referenced anywhere, so when you compile the binary yourself, you can use any name.
> 
> @fabpot I just run `go generate` then `go build` and this the filename I got

Of course, I never run `go build` without `-o` :)

**Comment by yguedidi** [comment]
> > > I don't think this is useful as this name is not referenced anywhere, so when you compile the binary yourself, you can use any name.
> > 
> > 
> > @fabpot I just run `go generate` then `go build` and this the filename I got
> 
> Of course, I never run `go build` without `-o` :)

Because you're way more experienced in Go, me it was the first time writing Go, not even in tutorials, I'm quite proud even for just few lines :)

**Pull request merged**
