### PR TITLE
Update Go to 1.22

### PR DESCRIPTION
**Pull request by tucksaun**
WIP as we need to the PR in the libraries repos to be merged first:
- [x] https://github.com/symfony-cli/cert/pull/8
- [x] https://github.com/symfony-cli/console/pull/7
- [x] https://github.com/symfony-cli/dumper/pull/5
- [x] https://github.com/symfony-cli/phpstore/pull/15
- [x] https://github.com/symfony-cli/terminal/pull/10

### CODE REVIEW

**Comment by fabpot** [comment]
All other PRs merged (and green).

**Comment by tucksaun** [comment]
Thanks Fabien.
Do you want to tag the libraries before merging this one?

**Comment by fabpot** [comment]
> Thanks Fabien. Do you want to tag the libraries before merging this one?

I don't think this is needed as there are no changes in these libraries.

**Comment by tucksaun** [comment]
> > Thanks Fabien. Do you want to tag the libraries before merging this one?
> 
> I don't think this is needed as there are no changes in these libraries.

I agree 👍

**Pull request merged**
