### PR TITLE
Add docker image

### PR DESCRIPTION
**Pull request by shyim**
To improve #205

### CODE REVIEW

**Comment by shyim** [comment]
i guess you to have to release it first time manually to give the CI access. See package settings as example

**Comment by tucksaun** [comment]
@shyim I will probably have a couple of suggestions to make.
do you prefer a PR to your fork or suggestions directly within this PR?

**Comment by shyim** [comment]
image
You should be able to push directly in my branch if you are maintainer :)

**Comment by tucksaun** [comment]
@shyim hehe but I'm not maintainer 😆

**Comment by fabpot** [comment]
@tucksaun Looks like you've just been promoted ;)

**Comment by tucksaun** [comment]
@fabpot @shyim I just pushed some fixes and tweaks.

@fabpot: do not merge it yet though because GitHub actions are not running `gorelease build` for PR (working on it), so we can't be sure yet everything works properly on the CI.

**Comment by tucksaun** [comment]
this will fix #101 as well

**Comment by tucksaun** [comment]
I added multiarch support, TLS certificates into the image so that external communications (new version checking, security checks, etc) work and tried to optimize to get the least layers possible.

And the CI is green, we will need to see how first release on GHCR works though.

@shyim @fabpot ready for review I guess.

**Pull request merged**
